### PR TITLE
Add BookDetails, AuthorDetails page

### PR DESCRIPTION
**Pull request by Akshay02022**
Issue #1 

Add Book Detail Page for Books in BookShelf.
Add Author Detail Page.
Add Rating of a Book in Book Detail Page.

### CODE REVIEW

**Comment by Akshay02022** [comment]
Hey @AKASH-PRASAD7 ,
Could you assist me in understanding why the checks are failing? I'm relatively new to Git and GitHub, and I'd appreciate guidance on how to address these failed checks.

**Comment by AKASH-PRASAD7** [comment]
> Hey @AKASH-PRASAD7 , Could you assist me in understanding why the checks are failing? I'm relatively new to Git and GitHub, and I'd appreciate guidance on how to address these failed checks.

Don't worry about the checks, I will fix it myself.

**Comment by Akshay02022** [comment]
Thank you for handling the checks.
If everything looks fine, please go ahead and merge the PR.
However, if it's not too much trouble, I'd still be grateful if you could briefly explain why the checks failed and share some insights on how to address them. This would be immensely helpful for my future contributions, and I'm eager to learn from this experience.

**Comment by AKASH-PRASAD7** [comment]
> Thank you for handling the checks. If everything looks fine, please go ahead and merge the PR. However, if it's not too much trouble, I'd still be grateful if you could briefly explain why the checks failed and share some insights on how to address them. This would be immensely helpful for my future contributions, and I'm eager to learn from this experience.

Yeah, I will merge it soon, and thanks for your contribution.

**Pull request merged**
